---
title: "OMDb programming overview"
author: "H. David Shea"
date: "`r format(Sys.time(), '%d %b %Y')`"
output:
  pdf_document:
    toc: yes
  html_document:
    fig.align: center
    fig_caption: yes
    fig_height: 5
    fig_width: 9
    highlight: tango
    theme: spacelab
    code_folding: hide
---

```{r setup, include=FALSE}
library(tidyverse)
library(knitr)

knitr::opts_chunk$set(
    comment = "#>", 
    collapse = TRUE, 
    message = FALSE,
    fig.width = 8,
    fig.asp = ((1 + sqrt(5)) / 2) - 1, # the golden ratio - technically, the b proportion of a+b when a is 1
    out.width = "70%",
    fig.align = "center"
)

qik_kable <- function(fld, fnm) {
    if (!is.na(fld)) {
        str_split(fld, ",[ ]*")[[1]] %>%
            as_tibble() %>%
            transmute_(fnm = "value") %>%
            kable()
    }
}

source("utils.R")

if(!set_api_key()) {
    stop("set_api_key() requies either a passed in OMDb API KEY or one stored in .cache/code.csv", 
         call. = FALSE)
}
```

# {.tabset .tabset-fade}

## Request by title

### Movie

```{r by_title_movie, include=TRUE, warning=FALSE}
entry <- get_by_title("Midnight in Paris", type = "movie")

entry %>%
    select(-Plot, -Poster, -Actors, -Director, -Writer, 
           -Genre, -Production, -Language, -Country, - Website, -totalSeasons) %>%
    kable(caption = entry$Title)

entry %>% 
        select(Plot) %>% 
        kable()

str_split(entry$Actors, ",[ ]*")[[1]] %>%
    as_tibble() %>% 
    transmute(Actors = value) %>%
    kable()

str_split(entry$Director, ",[ ]*")[[1]] %>%
    as_tibble() %>% 
    transmute(Director = value) %>%
    kable()

str_split(entry$Writer, ",[ ]*")[[1]] %>%
    as_tibble() %>% 
    transmute(Writer = value) %>%
    kable()

str_split(entry$Production, ",[ ]*")[[1]] %>%
    as_tibble() %>% 
    transmute(Production = value) %>%
    kable()

str_split(entry$Language, ",[ ]*")[[1]] %>%
    as_tibble() %>%
    transmute(Language = value) %>%
    kable()

str_split(entry$Country, ",[ ]*")[[1]] %>%
    as_tibble() %>%
    transmute(Country = value) %>%
    kable()

str_split(entry$Genre, ",[ ]*")[[1]] %>%
    as_tibble() %>%
    transmute(Genre = value) %>%
    kable()
```

### Series

```{r by_title_series, include=TRUE, warning=FALSE}
entry <- get_by_title("Doctor Who", type = "series")

entry %>%
    select(-Plot, -Poster, -Actors, -Director, -Writer, 
           -Genre, -Production, -Language, -Country, - Website, -totalSeasons) %>%
    kable(caption = entry$Title)

entry %>% 
        select(Plot) %>% 
        kable()

str_split(entry$Actors, ",[ ]*")[[1]] %>%
    as_tibble() %>% 
    transmute(Actors = value) %>%
    kable()

str_split(entry$Director, ",[ ]*")[[1]] %>%
    as_tibble() %>% 
    transmute(Director = value) %>%
    kable()

str_split(entry$Writer, ",[ ]*")[[1]] %>%
    as_tibble() %>% 
    transmute(Writer = value) %>%
    kable()

str_split(entry$Production, ",[ ]*")[[1]] %>%
    as_tibble() %>% 
    transmute(Production = value) %>%
    kable()

str_split(entry$Language, ",[ ]*")[[1]] %>%
    as_tibble() %>%
    transmute(Language = value) %>%
    kable()

str_split(entry$Country, ",[ ]*")[[1]] %>%
    as_tibble() %>%
    transmute(Country = value) %>%
    kable()

str_split(entry$Genre, ",[ ]*")[[1]] %>%
    as_tibble() %>%
    transmute(Genre = value) %>%
    kable()
```

## Request by id

### Movie

```{r by_id_movie, include=TRUE, warning=FALSE}
entry <- get_by_id("tt0073486")

entry %>%
    select(-Plot, -Poster, -Actors, -Director, -Writer, 
           -Genre, -Production, -Language, -Country, - Website, -totalSeasons) %>%
    kable(caption = entry$Title)

entry %>% 
        select(Plot) %>% 
        kable()

str_split(entry$Actors, ",[ ]*")[[1]] %>%
    as_tibble() %>% 
    transmute(Actors = value) %>%
    kable()

str_split(entry$Director, ",[ ]*")[[1]] %>%
    as_tibble() %>% 
    transmute(Director = value) %>%
    kable()

str_split(entry$Writer, ",[ ]*")[[1]] %>%
    as_tibble() %>% 
    transmute(Writer = value) %>%
    kable()

str_split(entry$Production, ",[ ]*")[[1]] %>%
    as_tibble() %>% 
    transmute(Production = value) %>%
    kable()

str_split(entry$Language, ",[ ]*")[[1]] %>%
    as_tibble() %>%
    transmute(Language = value) %>%
    kable()

str_split(entry$Country, ",[ ]*")[[1]] %>%
    as_tibble() %>%
    transmute(Country = value) %>%
    kable()

str_split(entry$Genre, ",[ ]*")[[1]] %>%
    as_tibble() %>%
    transmute(Genre = value) %>%
    kable()
```

### Series

```{r by_id_series, include=TRUE, warning=FALSE}
entry <- get_by_id("tt0453422")

entry %>%
    select(-Plot, -Poster, -Actors, -Director, -Writer, 
           -Genre, -Production, -Language, -Country, - Website, -totalSeasons) %>%
    kable(caption = entry$Title)

entry %>% 
        select(Plot) %>% 
        kable()

str_split(entry$Actors, ",[ ]*")[[1]] %>%
    as_tibble() %>% 
    transmute(Actors = value) %>%
    kable()

str_split(entry$Director, ",[ ]*")[[1]] %>%
    as_tibble() %>% 
    transmute(Director = value) %>%
    kable()

str_split(entry$Writer, ",[ ]*")[[1]] %>%
    as_tibble() %>% 
    transmute(Writer = value) %>%
    kable()

str_split(entry$Production, ",[ ]*")[[1]] %>%
    as_tibble() %>% 
    transmute(Production = value) %>%
    kable()

str_split(entry$Language, ",[ ]*")[[1]] %>%
    as_tibble() %>%
    transmute(Language = value) %>%
    kable()

str_split(entry$Country, ",[ ]*")[[1]] %>%
    as_tibble() %>%
    transmute(Country = value) %>%
    kable()

str_split(entry$Genre, ",[ ]*")[[1]] %>%
    as_tibble() %>%
    transmute(Genre = value) %>%
    kable()
```

### Game

```{r by_id_game, include=TRUE, warning=FALSE}

entry %>%
    select(-Plot, -Poster, -Actors, -Director, -Writer, 
           -Genre, -Production, -Language, -Country, - Website, -totalSeasons) %>%
    kable(caption = entry$Title)

entry %>% 
        select(Plot) %>% 
        kable()

str_split(entry$Actors, ",[ ]*")[[1]] %>%
    as_tibble() %>% 
    transmute(Actors = value) %>%
    kable()

str_split(entry$Director, ",[ ]*")[[1]] %>%
    as_tibble() %>% 
    transmute(Director = value) %>%
    kable()

str_split(entry$Writer, ",[ ]*")[[1]] %>%
    as_tibble() %>% 
    transmute(Writer = value) %>%
    kable()

str_split(entry$Production, ",[ ]*")[[1]] %>%
    as_tibble() %>% 
    transmute(Production = value) %>%
    kable()

str_split(entry$Language, ",[ ]*")[[1]] %>%
    as_tibble() %>%
    transmute(Language = value) %>%
    kable()

str_split(entry$Country, ",[ ]*")[[1]] %>%
    as_tibble() %>%
    transmute(Country = value) %>%
    kable()

str_split(entry$Genre, ",[ ]*")[[1]] %>%
    as_tibble() %>%
    transmute(Genre = value) %>%
    kable()
```

## Search by title

```{r search_by_title, include=TRUE, warning=FALSE}
s <- "Fast & Furious"
p <- 1
results <- tibble::tibble(.rows = 0)
while(!identical((res <- search_by_title(s, type="movie", page=p)), tibble::tibble(.rows = 0))) {
    results <- rbind(results, res)
    p <- p + 1
}

results %>%
    arrange(Title, Year) %>% 
    kable(caption = str_c("Entries with '",s,"' in the title."))
```
